import { mkdtempSync, readdirSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { parseSchema } from "@ember/schema";
import { findModel } from "@ember/ast";
import { FirebirdDialect } from "@ember/sql";
import type { SqlDriver, TransactionContext } from "@ember/driver";
import {
  FirebirdDdl,
  Migrator,
  diffSchemas,
  planMigration,
  renderMigrationSql,
  splitStatements,
} from "@ember/migrate";

const dialect = new FirebirdDialect();

const DESIRED = parseSchema(`model User {
  id    Int    @id @default(autoincrement())
  email String @unique @db.VarChar(255)
  name  String?
  @@map("USERS")
}

model Post {
  id       Int    @id @default(autoincrement())
  title    String @db.VarChar(200)
  authorId Int    @map("AUTHOR_ID")
  author   User   @relation(fields: [authorId], references: [id], onDelete: Cascade)
}`);

describe("DDL generator", () => {
  const ddl = new FirebirdDdl(dialect);
  it("creates a table with identity PK and native types", () => {
    const sql = ddl.createTable(findModel(DESIRED, "User")!);
    expect(sql).toContain('CREATE TABLE "USERS"');
    expect(sql).toContain('"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    expect(sql).toContain('"EMAIL" VARCHAR(255) NOT NULL');
    expect(sql).toContain('"NAME" VARCHAR(255)'); // nullable: no NOT NULL
    expect(sql).toContain('PRIMARY KEY ("ID")');
  });

  it("builds ALTER and FK statements", () => {
    const post = findModel(DESIRED, "Post")!;
    const title = post.fields.find((f) => f.name === "title")!;
    expect(ddl.addColumn("POST", title)).toBe(
      'ALTER TABLE "POST" ADD "TITLE" VARCHAR(200) NOT NULL',
    );
    expect(ddl.alterColumnType("POST", title)).toContain("ALTER COLUMN \"TITLE\" TYPE VARCHAR(200)");
    const fk = ddl.addForeignKey("POST", "FK_X", ["AUTHOR_ID"], "USERS", ["ID"], "Cascade");
    expect(fk).toContain('FOREIGN KEY ("AUTHOR_ID") REFERENCES "USERS" ("ID")');
    expect(fk).toContain("ON DELETE CASCADE");
  });
});

describe("schema diff", () => {
  it("treats an empty database as all-created", () => {
    const diff = diffSchemas(DESIRED, { generators: [], enums: [], models: [] });
    expect(diff.createdModels.map((m) => m.name)).toEqual(["User", "Post"]);
    expect(diff.droppedTables).toEqual([]);
  });

  it("detects added/changed columns and added constraints", () => {
    // current: USERS exists but lacks `name` and email is plain VARCHAR(100)
    const current = parseSchema(`model User {
      id    Int    @id
      email String @db.VarChar(100)
      @@map("USERS")
    }`);
    const diff = diffSchemas(DESIRED, current);
    const userChange = diff.modelChanges.find((c) => c.table === "USERS")!;
    expect(userChange.addedColumns.map((f) => f.name)).toContain("name");
    expect(userChange.changedColumns.map((c) => c.field.name)).toContain("email");
    expect(userChange.addedUniques.some((u) => u.columns.includes("EMAIL"))).toBe(true);
    // Post is brand new
    expect(diff.createdModels.map((m) => m.name)).toEqual(["Post"]);
  });

  it("detects dropped tables", () => {
    const current = parseSchema(`model User {
      id Int @id
      @@map("USERS")
    }

    model Legacy {
      id Int @id
      @@map("LEGACY")
    }`);
    const diff = diffSchemas(
      parseSchema(`model User { id Int @id @@map("USERS") }`),
      current,
    );
    expect(diff.droppedTables).toEqual(["LEGACY"]);
  });
});

describe("planner", () => {
  it("emits foreign keys after table creation", () => {
    const diff = diffSchemas(DESIRED, { generators: [], enums: [], models: [] });
    const stmts = planMigration(diff, DESIRED, dialect);
    const createUsers = stmts.findIndex((s) => /CREATE TABLE "USERS"/.test(s));
    const createPost = stmts.findIndex((s) => /CREATE TABLE "POST"/.test(s));
    const fk = stmts.findIndex((s) => /FOREIGN KEY/.test(s));
    expect(createUsers).toBeGreaterThanOrEqual(0);
    expect(createPost).toBeGreaterThanOrEqual(0);
    expect(fk).toBeGreaterThan(createUsers);
    expect(fk).toBeGreaterThan(createPost);
  });

  it("round-trips through render/split", () => {
    const diff = diffSchemas(DESIRED, { generators: [], enums: [], models: [] });
    const stmts = planMigration(diff, DESIRED, dialect);
    const body = renderMigrationSql(stmts);
    expect(splitStatements(body)).toEqual(stmts);
  });
});

// ---- Migrator orchestration (mock driver) ---------------------------------

class MockDriver implements SqlDriver {
  public statements: string[] = [];
  async connect() {}
  async disconnect() {}
  async transaction<T>(fn: (tx: TransactionContext) => Promise<T>): Promise<T> {
    const tx: TransactionContext = {
      query: async (sql) => {
        this.statements.push(sql);
        if (/COUNT\(\*\) AS N/.test(sql)) return [{ N: 0 }] as any; // history missing
        if (/RDB\$RELATION/.test(sql)) return [] as any; // empty introspection
        return [] as any;
      },
    };
    return fn(tx);
  }
}

describe("Migrator", () => {
  it("dev writes a migration file and applies the DDL", async () => {
    const dir = mkdtempSync(join(tmpdir(), "ember-mig-"));
    const driver = new MockDriver();
    const migrator = new Migrator(driver, DESIRED, dir, dialect);

    const result = await migrator.dev("init");
    expect(result.empty).toBe(false);
    expect(result.statements.length).toBeGreaterThan(0);

    // a migration folder with migration.sql was written
    const folders = readdirSync(dir);
    expect(folders).toHaveLength(1);
    const sql = readFileSync(join(dir, folders[0]!, "migration.sql"), "utf8");
    expect(sql).toContain('CREATE TABLE "USERS"');

    // the DDL plus a history INSERT were executed against the driver
    expect(driver.statements.some((s) => /CREATE TABLE "USERS"/.test(s))).toBe(true);
    expect(driver.statements.some((s) => /INSERT INTO "_EMBER_MIGRATIONS"/.test(s))).toBe(true);
  });

  it("dev reports an empty diff when schema matches the database", async () => {
    // introspection returns the same shape -> plan() must be empty.
    const dir = mkdtempSync(join(tmpdir(), "ember-mig-"));
    const SIMPLE = parseSchema(`model Tag { id Int @id @@map("TAG") }`);

    class MatchDriver implements SqlDriver {
      async connect() {}
      async disconnect() {}
      async transaction<T>(fn: (tx: TransactionContext) => Promise<T>): Promise<T> {
        const tx: TransactionContext = {
          query: async (sql) => {
            if (/COUNT\(\*\) AS N/.test(sql)) return [{ N: 1 }] as any;
            // Order matters: the columns query references both RELATION_FIELDS
            // and RELATIONS, so match the more specific tables first.
            if (/RDB\$RELATION_FIELDS/.test(sql))
              return [
                {
                  TABLE_NAME: "TAG",
                  FIELD_NAME: "ID",
                  FIELD_POSITION: 0,
                  NULL_FLAG: 1,
                  FIELD_TYPE: 8,
                  IDENTITY_TYPE: null,
                },
              ] as any;
            if (/RDB\$RELATION_CONSTRAINTS/.test(sql))
              return [
                {
                  CONSTRAINT_NAME: "PK_TAG",
                  CONSTRAINT_TYPE: "PRIMARY KEY",
                  TABLE_NAME: "TAG",
                  INDEX_NAME: "PK_TAG",
                  FIELD_NAME: "ID",
                  SEG_POSITION: 0,
                },
              ] as any;
            if (/RDB\$RELATIONS/.test(sql))
              return [{ "RDB$RELATION_NAME": "TAG" }] as any;
            return [] as any;
          },
        };
        return fn(tx);
      }
    }

    const migrator = new Migrator(new MatchDriver(), SIMPLE, dir, dialect);
    const result = await migrator.dev("noop");
    expect(result.empty).toBe(true);
    expect(existsSync(join(dir, "."))).toBe(true);
    expect(readdirSync(dir)).toHaveLength(0);
  });
});
