import { mkdtempSync, readdirSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { parseSchema } from "@ember/schema";
import { findModel } from "@ember/ast";
import { FirebirdDialect } from "@ember/sql";
import type { SqlDriver, TransactionContext } from "@ember/driver";
import {
  FirebirdDdl,
  Migrator,
  diffSchemas,
  planMigration,
  renderMigrationSql,
  splitStatements,
} from "@ember/migrate";

const dialect = new FirebirdDialect();

function parseScema21() {
  return findModel(
    parseSchema(`model Account {
      id      Int     @id @default(autoincrement())
      enabled Boolean @default(true)
    }`),
    "Account",
  )!;
}

const DESIRED = parseSchema(`model User {
  id    Int    @id @default(autoincrement())
  email String @unique @db.VarChar(255)
  name  String?
  @@map("USERS")
}

model Post {
  id       Int    @id @default(autoincrement())
  title    String @db.VarChar(200)
  authorId Int    @map("AUTHOR_ID")
  author   User   @relation(fields: [authorId], references: [id], onDelete: Cascade)
}`);

describe("DDL generator", () => {
  const ddl = new FirebirdDdl(dialect);
  it("creates a table with identity PK and native types", () => {
    const sql = ddl.createTable(findModel(DESIRED, "User")!);
    expect(sql).toContain('CREATE TABLE "USERS"');
    expect(sql).toContain('"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    expect(sql).toContain('"EMAIL" VARCHAR(255) NOT NULL');
    expect(sql).toContain('"NAME" VARCHAR(255)'); // nullable: no NOT NULL
    expect(sql).toContain('PRIMARY KEY ("ID")');
  });

  it("emits SMALLINT booleans and a sequence+trigger on Firebird 2.1", () => {
    const v21 = new FirebirdDialect({ version: "2.1" });
    const ddl21 = new FirebirdDdl(v21);
    const schema = parseScema21();
    const create = ddl21.createTable(schema);
    // identity column has no inline IDENTITY clause on 2.1
    expect(create).not.toContain("IDENTITY");
    expect(create).toContain('"ENABLED" SMALLINT');

    const objs = ddl21.autoIncrementObjects(schema);
    expect(objs.some((s) => /CREATE SEQUENCE/.test(s))).toBe(true);
    const trigger = objs.find((s) => /CREATE TRIGGER/.test(s))!;
    expect(trigger).toContain("BEFORE INSERT");
    expect(trigger).toContain("GEN_ID(");
    expect(trigger).toContain("NEW.\"ID\" IS NULL");
  });

  it("uses ALTER COLUMN SET/DROP NOT NULL on Firebird 3+", () => {
    expect(ddl.setNotNull("POST", "TITLE", true)).toBe(
      'ALTER TABLE "POST" ALTER COLUMN "TITLE" SET NOT NULL',
    );
    expect(ddl.setNotNull("POST", "TITLE", false)).toBe(
      'ALTER TABLE "POST" ALTER COLUMN "TITLE" DROP NOT NULL',
    );
  });

  it("toggles the NOT NULL flag via the catalog on Firebird 2.5", () => {
    const ddl25 = new FirebirdDdl(new FirebirdDialect({ version: "2.5" }));
    expect(ddl25.setNotNull("POST", "TITLE", true)).toBe(
      "UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = 1 " +
        "WHERE RDB$RELATION_NAME = 'POST' AND RDB$FIELD_NAME = 'TITLE'",
    );
    expect(ddl25.setNotNull("POST", "TITLE", false)).toBe(
      "UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = NULL " +
        "WHERE RDB$RELATION_NAME = 'POST' AND RDB$FIELD_NAME = 'TITLE'",
    );
  });

  it("builds ALTER and FK statements", () => {
    const post = findModel(DESIRED, "Post")!;
    const title = post.fields.find((f) => f.name === "title")!;
    expect(ddl.addColumn("POST", title)).toBe(
      'ALTER TABLE "POST" ADD "TITLE" VARCHAR(200) NOT NULL',
    );
    expect(ddl.alterColumnType("POST", title)).toContain("ALTER COLUMN \"TITLE\" TYPE VARCHAR(200)");
    const fk = ddl.addForeignKey("POST", "FK_X", ["AUTHOR_ID"], "USERS", ["ID"], "Cascade");
    expect(fk).toContain('FOREIGN KEY ("AUTHOR_ID") REFERENCES "USERS" ("ID")');
    expect(fk).toContain("ON DELETE CASCADE");
  });
});

describe("schema diff", () => {
  it("treats an empty database as all-created", () => {
    const diff = diffSchemas(DESIRED, { generators: [], enums: [], models: [] });
    expect(diff.createdModels.map((m) => m.name)).toEqual(["User", "Post"]);
    expect(diff.droppedTables).toEqual([]);
  });

  it("detects added/changed columns and added constraints", () => {
    // current: USERS exists but lacks `name` and email is plain VARCHAR(100)
    const current = parseSchema(`model User {
      id    Int    @id
      email String @db.VarChar(100)
      @@map("USERS")
    }`);
    const diff = diffSchemas(DESIRED, current);
    const userChange = diff.modelChanges.find((c) => c.table === "USERS")!;
    expect(userChange.addedColumns.map((f) => f.name)).toContain("name");
    expect(userChange.changedColumns.map((c) => c.field.name)).toContain("email");
    expect(userChange.addedUniques.some((u) => u.columns.includes("EMAIL"))).toBe(true);
    // Post is brand new
    expect(diff.createdModels.map((m) => m.name)).toEqual(["Post"]);
  });

  it("detects autoincrement added to an existing column", () => {
    const current = parseSchema(`model VendasEntrega {
      idempresa Int @map("IDEMPRESA")
      idvenda   Int @map("IDVENDA")
      @@id([idempresa, idvenda])
      @@map("VENDAS_ENTREGA")
    }`);
    const desired = parseSchema(`model VendasEntrega {
      idempresa Int @map("IDEMPRESA")
      idvenda   Int @default(autoincrement()) @map("IDVENDA")
      @@id([idempresa, idvenda])
      @@map("VENDAS_ENTREGA")
    }`);
    const change = diffSchemas(desired, current).modelChanges.find(
      (c) => c.table === "VENDAS_ENTREGA",
    )!;
    const cc = change.changedColumns.find((c) => c.field.name === "idvenda")!;
    expect(cc.identityAdded).toBe(true);
    expect(cc.typeChanged).toBe(false);
    expect(cc.nullabilityChanged).toBe(false);
  });

  it("does not flag autoincrement when the column already has it", () => {
    const schema = parseSchema(`model VendasEntrega {
      idempresa Int @map("IDEMPRESA")
      idvenda   Int @default(autoincrement()) @map("IDVENDA")
      @@id([idempresa, idvenda])
      @@map("VENDAS_ENTREGA")
    }`);
    const diff = diffSchemas(schema, schema);
    expect(diff.modelChanges).toEqual([]);
  });

  it("does not emit a nullability change for a nullable-declared composite PK column", () => {
    // The DB enforces NOT NULL on PK columns, so introspection reports them as
    // required even when the schema declares them `Int?`. The diff must not try
    // to drop NOT NULL (a no-op the engine ignores, re-emitted every run).
    const desired = parseSchema(`model ComprasNotaRef {
      idempresa Int? @map("IDEMPRESA")
      idcompra  Int? @map("IDCOMPRA")
      iditem    Int? @map("IDITEM")
      @@id([idempresa, idcompra, iditem])
      @@map("COMPRAS_NOTA_REF")
    }`);
    const current = parseSchema(`model ComprasNotaRef {
      idempresa Int @map("IDEMPRESA")
      idcompra  Int @map("IDCOMPRA")
      iditem    Int @map("IDITEM")
      @@id([idempresa, idcompra, iditem])
      @@map("COMPRAS_NOTA_REF")
    }`);
    const diff = diffSchemas(desired, current);
    expect(diff.modelChanges).toEqual([]);
  });

  it("detects dropped tables", () => {
    const current = parseSchema(`model User {
      id Int @id
      @@map("USERS")
    }

    model Legacy {
      id Int @id
      @@map("LEGACY")
    }`);
    const diff = diffSchemas(
      parseSchema(`model User { id Int @id @@map("USERS") }`),
      current,
    );
    expect(diff.droppedTables).toEqual(["LEGACY"]);
  });
});

describe("planner", () => {
  it("emits foreign keys after table creation", () => {
    const diff = diffSchemas(DESIRED, { generators: [], enums: [], models: [] });
    const stmts = planMigration(diff, DESIRED, dialect);
    const createUsers = stmts.findIndex((s) => /CREATE TABLE "USERS"/.test(s));
    const createPost = stmts.findIndex((s) => /CREATE TABLE "POST"/.test(s));
    const fk = stmts.findIndex((s) => /FOREIGN KEY/.test(s));
    expect(createUsers).toBeGreaterThanOrEqual(0);
    expect(createPost).toBeGreaterThanOrEqual(0);
    expect(fk).toBeGreaterThan(createUsers);
    expect(fk).toBeGreaterThan(createPost);
  });

  it("emits a sequence + BEFORE INSERT trigger when identity is added to a column", () => {
    const current = parseSchema(`model VendasEntrega {
      idempresa Int @map("IDEMPRESA")
      idvenda   Int @map("IDVENDA")
      @@id([idempresa, idvenda])
      @@map("VENDAS_ENTREGA")
    }`);
    const desired = parseSchema(`model VendasEntrega {
      idempresa Int @map("IDEMPRESA")
      idvenda   Int @default(autoincrement()) @map("IDVENDA")
      @@id([idempresa, idvenda])
      @@map("VENDAS_ENTREGA")
    }`);
    const v25 = new FirebirdDialect({ version: "2.5" });
    const stmts = planMigration(diffSchemas(desired, current), desired, v25);
    expect(stmts.some((s) => /CREATE SEQUENCE "GEN_VENDAS_ENTREGA_IDVENDA"/.test(s))).toBe(true);
    const trigger = stmts.find((s) => /CREATE TRIGGER/.test(s))!;
    expect(trigger).toContain("BEFORE INSERT");
    expect(trigger).toContain('NEW."IDVENDA" = GEN_ID("GEN_VENDAS_ENTREGA_IDVENDA", 1)');
  });

  it("round-trips through render/split", () => {
    const diff = diffSchemas(DESIRED, { generators: [], enums: [], models: [] });
    const stmts = planMigration(diff, DESIRED, dialect);
    const body = renderMigrationSql(stmts);
    expect(splitStatements(body)).toEqual(stmts);
  });

  it("preserves PSQL trigger bodies (internal semicolons) across render/split", () => {
    const stmts = [
      'CREATE TABLE "T" ("ID" INTEGER NOT NULL)',
      'CREATE TRIGGER "T_BI" FOR "T" ACTIVE BEFORE INSERT POSITION 0 AS\n' +
        "BEGIN\n  IF (NEW.\"ID\" IS NULL) THEN NEW.\"ID\" = GEN_ID(GEN_T, 1);\nEND",
    ];
    const body = renderMigrationSql(stmts);
    const split = splitStatements(body);
    expect(split).toHaveLength(2);
    expect(split[1]).toContain("GEN_ID(GEN_T, 1);"); // internal ; survived
  });
});

// ---- Migrator orchestration (mock driver) ---------------------------------

class MockDriver implements SqlDriver {
  public statements: string[] = [];
  async connect() {}
  async disconnect() {}
  async transaction<T>(fn: (tx: TransactionContext) => Promise<T>): Promise<T> {
    const tx: TransactionContext = {
      query: async (sql) => {
        this.statements.push(sql);
        if (/COUNT\(\*\) AS N/.test(sql)) return [{ N: 0 }] as any; // history missing
        if (/RDB\$RELATION/.test(sql)) return [] as any; // empty introspection
        return [] as any;
      },
    };
    return fn(tx);
  }
}

describe("Migrator", () => {
  it("dev writes a migration file and applies the DDL", async () => {
    const dir = mkdtempSync(join(tmpdir(), "ember-mig-"));
    const driver = new MockDriver();
    const migrator = new Migrator(driver, DESIRED, dir, dialect);

    const result = await migrator.dev("init");
    expect(result.empty).toBe(false);
    expect(result.statements.length).toBeGreaterThan(0);

    // a migration folder with migration.sql was written
    const folders = readdirSync(dir);
    expect(folders).toHaveLength(1);
    const sql = readFileSync(join(dir, folders[0]!, "migration.sql"), "utf8");
    expect(sql).toContain('CREATE TABLE "USERS"');

    // the DDL plus a history INSERT were executed against the driver
    expect(driver.statements.some((s) => /CREATE TABLE "USERS"/.test(s))).toBe(true);
    expect(driver.statements.some((s) => /INSERT INTO "_EMBER_MIGRATIONS"/.test(s))).toBe(true);
  });

  it("logs each statement when a logger is provided", async () => {
    const dir = mkdtempSync(join(tmpdir(), "ember-mig-"));
    const logged: string[] = [];
    const migrator = new Migrator(new MockDriver(), DESIRED, dir, dialect, {
      log: (m) => logged.push(m),
    });

    await migrator.dev("init");
    expect(logged.some((m) => /CREATE TABLE "USERS"/.test(m))).toBe(true);
    expect(logged.every((m) => /^-- step \d+\/\d+/.test(m))).toBe(true);
  });

  it("surfaces the offending statement when a step fails", async () => {
    const dir = mkdtempSync(join(tmpdir(), "ember-mig-"));

    class FailingDriver implements SqlDriver {
      async connect() {}
      async disconnect() {}
      async transaction<T>(fn: (tx: TransactionContext) => Promise<T>): Promise<T> {
        const tx: TransactionContext = {
          query: async (sql) => {
            if (/COUNT\(\*\) AS N/.test(sql)) return [{ N: 0 }] as any;
            if (/RDB\$RELATION/.test(sql)) return [] as any;
            if (/CREATE TABLE "USERS"/.test(sql)) {
              throw new Error("Token unknown - line 1, column 62, NOT");
            }
            return [] as any;
          },
        };
        return fn(tx);
      }
    }

    const migrator = new Migrator(new FailingDriver(), DESIRED, dir, dialect);
    await expect(migrator.dev("init")).rejects.toThrow(
      /Migration step \d+\/\d+ failed:[\s\S]*CREATE TABLE[\s\S]*Token unknown/,
    );
  });

  it("dev creates the history table in a committed transaction before inserting", async () => {
    // Firebird does not expose uncommitted DDL to DML in the same transaction:
    // a table CREATEd in a transaction is "unknown" to any INSERT/SELECT until
    // that transaction commits. This driver models that rule so the test fails
    // if the history CREATE and its INSERT ever share one transaction again.
    const dir = mkdtempSync(join(tmpdir(), "ember-mig-"));

    class FirebirdLikeDriver implements SqlDriver {
      private committed = new Set<string>();
      async connect() {}
      async disconnect() {}
      async transaction<T>(
        fn: (tx: TransactionContext) => Promise<T>,
      ): Promise<T> {
        const pending = new Set<string>();
        const tableOf = (re: RegExp, sql: string) =>
          sql.match(re)?.[1];
        const tx: TransactionContext = {
          query: async (sql) => {
            if (/COUNT\(\*\) AS N/.test(sql))
              return [{ N: this.committed.has("_EMBER_MIGRATIONS") ? 1 : 0 }] as any;
            if (/RDB\$RELATION/.test(sql)) return [] as any;
            const created = tableOf(/CREATE TABLE "([^"]+)"/, sql);
            if (created) {
              pending.add(created);
              return [] as any;
            }
            const touched =
              tableOf(/INSERT INTO "([^"]+)"/, sql) ??
              tableOf(/FROM "([^"]+)"/, sql);
            if (touched && !this.committed.has(touched))
              throw new Error(
                `Dynamic SQL Error, SQL error code = -204, Table unknown, ${touched}`,
              );
            return [] as any;
          },
        };
        const result = await fn(tx);
        for (const t of pending) this.committed.add(t); // commit
        return result;
      }
    }

    const migrator = new Migrator(new FirebirdLikeDriver(), DESIRED, dir, dialect);
    const result = await migrator.dev("init");
    expect(result.empty).toBe(false);
  });

  it("dev reports an empty diff when schema matches the database", async () => {
    // introspection returns the same shape -> plan() must be empty.
    const dir = mkdtempSync(join(tmpdir(), "ember-mig-"));
    const SIMPLE = parseSchema(`model Tag { id Int @id @@map("TAG") }`);

    class MatchDriver implements SqlDriver {
      async connect() {}
      async disconnect() {}
      async transaction<T>(fn: (tx: TransactionContext) => Promise<T>): Promise<T> {
        const tx: TransactionContext = {
          query: async (sql) => {
            if (/COUNT\(\*\) AS N/.test(sql)) return [{ N: 1 }] as any;
            // Order matters: the columns query references both RELATION_FIELDS
            // and RELATIONS, so match the more specific tables first.
            if (/RDB\$RELATION_FIELDS/.test(sql))
              return [
                {
                  TABLE_NAME: "TAG",
                  FIELD_NAME: "ID",
                  FIELD_POSITION: 0,
                  NULL_FLAG: 1,
                  FIELD_TYPE: 8,
                  IDENTITY_TYPE: null,
                },
              ] as any;
            if (/RDB\$RELATION_CONSTRAINTS/.test(sql))
              return [
                {
                  CONSTRAINT_NAME: "PK_TAG",
                  CONSTRAINT_TYPE: "PRIMARY KEY",
                  TABLE_NAME: "TAG",
                  INDEX_NAME: "PK_TAG",
                  FIELD_NAME: "ID",
                  SEG_POSITION: 0,
                },
              ] as any;
            if (/RDB\$RELATIONS/.test(sql))
              return [{ "RDB$RELATION_NAME": "TAG" }] as any;
            return [] as any;
          },
        };
        return fn(tx);
      }
    }

    const migrator = new Migrator(new MatchDriver(), SIMPLE, dir, dialect);
    const result = await migrator.dev("noop");
    expect(result.empty).toBe(true);
    expect(existsSync(join(dir, "."))).toBe(true);
    expect(readdirSync(dir)).toHaveLength(0);
  });
});
