import {
  type DefaultValue,
  type FieldNode,
  type ModelNode,
  type ScalarType,
  fieldColumn,
  idFields,
  modelTable,
  scalarFields,
} from "@ember/ast";
import { type SqlDialect } from "@ember/sql";

/**
 * Generates Firebird DDL from schema nodes. Pure string generation (no I/O),
 * so it is fully unit-testable. Identifier quoting is delegated to the dialect
 * (Strategy) to stay backend-agnostic at the call sites.
 */
export class FirebirdDdl {
  constructor(private readonly d: SqlDialect) {}

  // ---- column types -------------------------------------------------------

  /** Firebird column type for a field, honoring its `@db.*` native type. */
  columnType(field: FieldNode): string {
    const native = field.nativeType;
    if (native) {
      const args = native.args.length ? `(${native.args.join(", ")})` : "";
      switch (native.name) {
        case "VarChar":
          return `VARCHAR${args || "(255)"}`;
        case "Char":
          return `CHAR${args || "(1)"}`;
        case "Text":
          return "BLOB SUB_TYPE TEXT";
        case "SmallInt":
          return "SMALLINT";
        case "Integer":
          return "INTEGER";
        case "BigInt":
          return "BIGINT";
        case "Float":
          return "FLOAT";
        case "DoublePrecision":
          return "DOUBLE PRECISION";
        case "Decimal":
          return `DECIMAL${args || "(18, 4)"}`;
        case "Boolean":
          return this.d.booleanColumnType();
        case "Date":
          return "DATE";
        case "Time":
          return "TIME";
        case "Timestamp":
          return "TIMESTAMP";
        case "Blob":
          return "BLOB SUB_TYPE BINARY";
      }
    }
    if (field.type === "Boolean") return this.d.booleanColumnType();
    return DEFAULT_DDL_TYPE[field.type as ScalarType] ?? "VARCHAR(255)";
  }

  /** `"COL" <type> [GENERATED ...] [DEFAULT ...] [NOT NULL]`. */
  columnDefinition(field: FieldNode): string {
    const parts = [this.d.quoteId(fieldColumn(field)), this.columnType(field)];
    if (isIdentity(field) && this.d.supportsIdentity) {
      parts.push("GENERATED BY DEFAULT AS IDENTITY");
    } else if (!isIdentity(field)) {
      const def = defaultClause(field.default);
      if (def) parts.push(def);
    }
    if (field.isRequired) parts.push("NOT NULL");
    return parts.join(" ");
  }

  /**
   * On Firebird 2.1/2.5 (no IDENTITY), emulate autoincrement with a SEQUENCE
   * and a BEFORE INSERT trigger. Returns the extra DDL objects to create after
   * the table; an empty array when IDENTITY is supported.
   */
  autoIncrementObjects(model: ModelNode): string[] {
    if (this.d.supportsIdentity) return [];
    const table = modelTable(model);
    const out: string[] = [];
    for (const field of scalarFields(model)) {
      if (isIdentity(field)) {
        out.push(...this.autoIncrementForColumn(table, fieldColumn(field)));
      }
    }
    return out;
  }

  autoIncrementForColumn(table: string, column: string): string[] {
    if (this.d.supportsIdentity) return [];
    const seq = capName(`GEN_${table}_${column}`);
    const trig = capName(`${table}_BI_${column}`);
    const qTable = this.d.quoteId(table);
    const qCol = this.d.quoteId(column);
    const qSeq = this.d.quoteId(seq);
    return [
      `CREATE SEQUENCE ${qSeq}`,
      `CREATE TRIGGER ${this.d.quoteId(trig)} FOR ${qTable} ACTIVE BEFORE INSERT POSITION 0 AS\n` +
        `BEGIN\n` +
        `  IF (NEW.${qCol} IS NULL) THEN NEW.${qCol} = GEN_ID(${qSeq}, 1);\n` +
        `END`,
    ];
  }

  // ---- table-level --------------------------------------------------------

  createTable(model: ModelNode): string {
    const cols = scalarFields(model).map((f) => "  " + this.columnDefinition(f));
    const pk = idFields(model);
    const lines = [...cols];
    if (pk.length > 0) {
      lines.push(
        `  PRIMARY KEY (${pk.map((f) => this.d.quoteId(fieldColumn(f))).join(", ")})`,
      );
    }
    return `CREATE TABLE ${this.d.quoteId(modelTable(model))} (\n${lines.join(",\n")}\n)`;
  }

  dropTable(table: string): string {
    return `DROP TABLE ${this.d.quoteId(table)}`;
  }

  addColumn(table: string, field: FieldNode): string {
    return `ALTER TABLE ${this.d.quoteId(table)} ADD ${this.columnDefinition(field)}`;
  }

  dropColumn(table: string, column: string): string {
    return `ALTER TABLE ${this.d.quoteId(table)} DROP ${this.d.quoteId(column)}`;
  }

  /** Change a column's data type (Firebird: ALTER COLUMN ... TYPE ...). */
  alterColumnType(table: string, field: FieldNode): string {
    return `ALTER TABLE ${this.d.quoteId(table)} ALTER COLUMN ${this.d.quoteId(
      fieldColumn(field),
    )} TYPE ${this.columnType(field)}`;
  }

  setNotNull(table: string, column: string, notNull: boolean): string {
    // Firebird 2.1/2.5 has no `ALTER COLUMN ... SET/DROP NOT NULL`; toggling the
    // NULL flag in the catalog is the supported equivalent on those servers.
    if (!this.d.supportsAlterNotNull) {
      return this.setNotNullViaCatalog(table, column, notNull);
    }
    const action = notNull ? "SET NOT NULL" : "DROP NOT NULL";
    return `ALTER TABLE ${this.d.quoteId(table)} ALTER COLUMN ${this.d.quoteId(
      column,
    )} ${action}`;
  }

  /** Firebird 2.1/2.5 NOT NULL toggle via the RDB$RELATION_FIELDS catalog. */
  private setNotNullViaCatalog(
    table: string,
    column: string,
    notNull: boolean,
  ): string {
    const flag = notNull ? "1" : "NULL";
    return (
      `UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = ${flag} ` +
      `WHERE RDB$RELATION_NAME = ${quoteLiteral(table)} ` +
      `AND RDB$FIELD_NAME = ${quoteLiteral(column)}`
    );
  }

  // ---- constraints & indexes ---------------------------------------------

  addUnique(table: string, name: string, columns: string[]): string {
    return `ALTER TABLE ${this.d.quoteId(table)} ADD CONSTRAINT ${this.d.quoteId(
      name,
    )} UNIQUE (${columns.map((c) => this.d.quoteId(c)).join(", ")})`;
  }

  dropConstraint(table: string, name: string): string {
    return `ALTER TABLE ${this.d.quoteId(table)} DROP CONSTRAINT ${this.d.quoteId(name)}`;
  }

  addForeignKey(
    table: string,
    name: string,
    columns: string[],
    refTable: string,
    refColumns: string[],
    onDelete?: string,
    onUpdate?: string,
  ): string {
    let sql = `ALTER TABLE ${this.d.quoteId(table)} ADD CONSTRAINT ${this.d.quoteId(
      name,
    )} FOREIGN KEY (${columns.map((c) => this.d.quoteId(c)).join(", ")}) REFERENCES ${this.d.quoteId(
      refTable,
    )} (${refColumns.map((c) => this.d.quoteId(c)).join(", ")})`;
    if (onUpdate) sql += ` ON UPDATE ${referentialSql(onUpdate)}`;
    if (onDelete) sql += ` ON DELETE ${referentialSql(onDelete)}`;
    return sql;
  }

  createIndex(
    table: string,
    name: string,
    columns: string[],
    unique: boolean,
  ): string {
    return `CREATE ${unique ? "UNIQUE " : ""}INDEX ${this.d.quoteId(name)} ON ${this.d.quoteId(
      table,
    )} (${columns.map((c) => this.d.quoteId(c)).join(", ")})`;
  }

  dropIndex(name: string): string {
    return `DROP INDEX ${this.d.quoteId(name)}`;
  }
}

// ---- helpers --------------------------------------------------------------

const DEFAULT_DDL_TYPE: Record<ScalarType, string> = {
  String: "VARCHAR(255)",
  Boolean: "BOOLEAN",
  Int: "INTEGER",
  BigInt: "BIGINT",
  Float: "DOUBLE PRECISION",
  Decimal: "DECIMAL(18, 4)",
  DateTime: "TIMESTAMP",
  Bytes: "BLOB SUB_TYPE BINARY",
  Json: "BLOB SUB_TYPE TEXT",
};

export function isIdentity(field: FieldNode): boolean {
  return field.default?.function?.name === "autoincrement";
}

/** Cap an identifier to Firebird's classic 31-char limit with a stable hash. */
function capName(name: string): string {
  const safe = name.replace(/[^A-Za-z0-9_]/g, "_");
  if (safe.length <= 31) return safe;
  let hash = 0;
  for (let i = 0; i < safe.length; i++) hash = (hash * 31 + safe.charCodeAt(i)) | 0;
  return `${safe.slice(0, 24)}_${Math.abs(hash).toString(36).slice(0, 6)}`;
}

/** Single-quote and escape a string for a SQL literal. */
function quoteLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function defaultClause(def: DefaultValue | undefined): string | null {
  if (!def) return null;
  if (def.function) {
    switch (def.function.name) {
      case "now":
        return "DEFAULT CURRENT_TIMESTAMP";
      case "uuid":
      case "cuid":
        return null; // generated app-side
      default:
        return null;
    }
  }
  if (def.literal === undefined) return null;
  if (typeof def.literal === "boolean") {
    return `DEFAULT ${def.literal ? "TRUE" : "FALSE"}`;
  }
  if (typeof def.literal === "number") return `DEFAULT ${def.literal}`;
  return `DEFAULT '${String(def.literal).replace(/'/g, "''")}'`;
}

function referentialSql(action: string): string {
  switch (action) {
    case "Cascade":
      return "CASCADE";
    case "SetNull":
      return "SET NULL";
    case "SetDefault":
      return "SET DEFAULT";
    case "NoAction":
      return "NO ACTION";
    case "Restrict":
      return "NO ACTION"; // Firebird has no RESTRICT; NO ACTION is closest
    default:
      return "NO ACTION";
  }
}
