import {
  type DefaultValue,
  type FieldNode,
  type ModelNode,
  type ScalarType,
  fieldColumn,
  idFields,
  modelTable,
  scalarFields,
} from "@ember/ast";
import { type SqlDialect } from "@ember/sql";

/**
 * Generates Firebird DDL from schema nodes. Pure string generation (no I/O),
 * so it is fully unit-testable. Identifier quoting is delegated to the dialect
 * (Strategy) to stay backend-agnostic at the call sites.
 */
export class FirebirdDdl {
  constructor(private readonly d: SqlDialect) {}

  // ---- column types -------------------------------------------------------

  /** Firebird column type for a field, honoring its `@db.*` native type. */
  columnType(field: FieldNode): string {
    const native = field.nativeType;
    if (native) {
      const args = native.args.length ? `(${native.args.join(", ")})` : "";
      switch (native.name) {
        case "VarChar":
          return `VARCHAR${args || "(255)"}`;
        case "Char":
          return `CHAR${args || "(1)"}`;
        case "Text":
          return "BLOB SUB_TYPE TEXT";
        case "SmallInt":
          return "SMALLINT";
        case "Integer":
          return "INTEGER";
        case "BigInt":
          return "BIGINT";
        case "Float":
          return "FLOAT";
        case "DoublePrecision":
          return "DOUBLE PRECISION";
        case "Decimal":
          return `DECIMAL${args || "(18, 4)"}`;
        case "Boolean":
          return "BOOLEAN";
        case "Date":
          return "DATE";
        case "Time":
          return "TIME";
        case "Timestamp":
          return "TIMESTAMP";
        case "Blob":
          return "BLOB SUB_TYPE BINARY";
      }
    }
    return DEFAULT_DDL_TYPE[field.type as ScalarType] ?? "VARCHAR(255)";
  }

  /** `"COL" <type> [GENERATED ...] [DEFAULT ...] [NOT NULL]`. */
  columnDefinition(field: FieldNode): string {
    const parts = [this.d.quoteId(fieldColumn(field)), this.columnType(field)];
    if (isIdentity(field)) {
      parts.push("GENERATED BY DEFAULT AS IDENTITY");
    } else {
      const def = defaultClause(field.default);
      if (def) parts.push(def);
    }
    if (field.isRequired) parts.push("NOT NULL");
    return parts.join(" ");
  }

  // ---- table-level --------------------------------------------------------

  createTable(model: ModelNode): string {
    const cols = scalarFields(model).map((f) => "  " + this.columnDefinition(f));
    const pk = idFields(model);
    const lines = [...cols];
    if (pk.length > 0) {
      lines.push(
        `  PRIMARY KEY (${pk.map((f) => this.d.quoteId(fieldColumn(f))).join(", ")})`,
      );
    }
    return `CREATE TABLE ${this.d.quoteId(modelTable(model))} (\n${lines.join(",\n")}\n)`;
  }

  dropTable(table: string): string {
    return `DROP TABLE ${this.d.quoteId(table)}`;
  }

  addColumn(table: string, field: FieldNode): string {
    return `ALTER TABLE ${this.d.quoteId(table)} ADD ${this.columnDefinition(field)}`;
  }

  dropColumn(table: string, column: string): string {
    return `ALTER TABLE ${this.d.quoteId(table)} DROP ${this.d.quoteId(column)}`;
  }

  /** Change a column's data type (Firebird: ALTER COLUMN ... TYPE ...). */
  alterColumnType(table: string, field: FieldNode): string {
    return `ALTER TABLE ${this.d.quoteId(table)} ALTER COLUMN ${this.d.quoteId(
      fieldColumn(field),
    )} TYPE ${this.columnType(field)}`;
  }

  setNotNull(table: string, column: string, notNull: boolean): string {
    const action = notNull ? "SET NOT NULL" : "DROP NOT NULL";
    return `ALTER TABLE ${this.d.quoteId(table)} ALTER COLUMN ${this.d.quoteId(
      column,
    )} ${action}`;
  }

  // ---- constraints & indexes ---------------------------------------------

  addUnique(table: string, name: string, columns: string[]): string {
    return `ALTER TABLE ${this.d.quoteId(table)} ADD CONSTRAINT ${this.d.quoteId(
      name,
    )} UNIQUE (${columns.map((c) => this.d.quoteId(c)).join(", ")})`;
  }

  dropConstraint(table: string, name: string): string {
    return `ALTER TABLE ${this.d.quoteId(table)} DROP CONSTRAINT ${this.d.quoteId(name)}`;
  }

  addForeignKey(
    table: string,
    name: string,
    columns: string[],
    refTable: string,
    refColumns: string[],
    onDelete?: string,
    onUpdate?: string,
  ): string {
    let sql = `ALTER TABLE ${this.d.quoteId(table)} ADD CONSTRAINT ${this.d.quoteId(
      name,
    )} FOREIGN KEY (${columns.map((c) => this.d.quoteId(c)).join(", ")}) REFERENCES ${this.d.quoteId(
      refTable,
    )} (${refColumns.map((c) => this.d.quoteId(c)).join(", ")})`;
    if (onUpdate) sql += ` ON UPDATE ${referentialSql(onUpdate)}`;
    if (onDelete) sql += ` ON DELETE ${referentialSql(onDelete)}`;
    return sql;
  }

  createIndex(
    table: string,
    name: string,
    columns: string[],
    unique: boolean,
  ): string {
    return `CREATE ${unique ? "UNIQUE " : ""}INDEX ${this.d.quoteId(name)} ON ${this.d.quoteId(
      table,
    )} (${columns.map((c) => this.d.quoteId(c)).join(", ")})`;
  }

  dropIndex(name: string): string {
    return `DROP INDEX ${this.d.quoteId(name)}`;
  }
}

// ---- helpers --------------------------------------------------------------

const DEFAULT_DDL_TYPE: Record<ScalarType, string> = {
  String: "VARCHAR(255)",
  Boolean: "BOOLEAN",
  Int: "INTEGER",
  BigInt: "BIGINT",
  Float: "DOUBLE PRECISION",
  Decimal: "DECIMAL(18, 4)",
  DateTime: "TIMESTAMP",
  Bytes: "BLOB SUB_TYPE BINARY",
  Json: "BLOB SUB_TYPE TEXT",
};

export function isIdentity(field: FieldNode): boolean {
  return field.default?.function?.name === "autoincrement";
}

function defaultClause(def: DefaultValue | undefined): string | null {
  if (!def) return null;
  if (def.function) {
    switch (def.function.name) {
      case "now":
        return "DEFAULT CURRENT_TIMESTAMP";
      case "uuid":
      case "cuid":
        return null; // generated app-side
      default:
        return null;
    }
  }
  if (def.literal === undefined) return null;
  if (typeof def.literal === "boolean") {
    return `DEFAULT ${def.literal ? "TRUE" : "FALSE"}`;
  }
  if (typeof def.literal === "number") return `DEFAULT ${def.literal}`;
  return `DEFAULT '${String(def.literal).replace(/'/g, "''")}'`;
}

function referentialSql(action: string): string {
  switch (action) {
    case "Cascade":
      return "CASCADE";
    case "SetNull":
      return "SET NULL";
    case "SetDefault":
      return "SET DEFAULT";
    case "NoAction":
      return "NO ACTION";
    case "Restrict":
      return "NO ACTION"; // Firebird has no RESTRICT; NO ACTION is closest
    default:
      return "NO ACTION";
  }
}
