import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  type EnumNode,
  type FieldNode,
  type ModelNode,
  type SchemaDocument,
  relationFields,
  scalarFields,
} from "@ember/ast";
import { lowerFirst } from "@ember/utils";
import { baseTsType } from "./ts-types";

export { baseTsType, fieldTsType } from "./ts-types";

/** The published runtime package the generated client imports from. */
const RUNTIME_PACKAGE = "@mateusseiboth/ember-orm";

/**
 * Generates a fully-typed TypeScript client from a schema. Produces per-model
 * scalar types, relation payloads, filter/where/select/include/create/update
 * input types, typed delegates, and the `EmberClient` class (which embeds the
 * schema so it can run with no extra wiring).
 */
export class ClientGenerator {
  constructor(private readonly schema: SchemaDocument) {}

  generate(): string {
    const parts: string[] = [];
    parts.push(this.header());
    parts.push(this.enums());
    parts.push(this.modelTypes());
    parts.push(this.registry());
    parts.push(PAYLOAD_RESOLVER);
    parts.push(this.namespace());
    parts.push(this.clientClass());
    return parts.filter(Boolean).join("\n\n") + "\n";
  }

  // ---- header & shared ----------------------------------------------------

  private header(): string {
    return `// AUTO-GENERATED by EmberORM. Do not edit by hand.
/* eslint-disable */
import { EmberClientBase } from "${RUNTIME_PACKAGE}/client";
import type { ClientOptions } from "${RUNTIME_PACKAGE}/client";

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | { [key: string]: JsonValue }
  | JsonValue[];

export type SortOrder = "asc" | "desc";
export type QueryMode = "default" | "insensitive";

const schemaDocument = ${JSON.stringify(this.schema)} as unknown as ClientOptions["schema"];`;
  }

  private enums(): string {
    return this.schema.enums.map((e) => this.enumType(e)).join("\n\n");
  }

  private enumType(node: EnumNode): string {
    const values = node.values.map((v) => `  ${v.name}: "${v.name}"`).join(",\n");
    return `export const ${node.name} = {\n${values}\n} as const;
export type ${node.name} = (typeof ${node.name})[keyof typeof ${node.name}];`;
  }

  private modelTypes(): string {
    return this.schema.models.map((m) => this.modelType(m)).join("\n\n");
  }

  private modelType(model: ModelNode): string {
    const scalars = scalarFields(model)
      .map((f) => `  ${f.name}: ${this.scalarType(f)};`)
      .join("\n");

    const lines: string[] = [];
    // Public model type is scalar-only; relations are resolved per-query.
    lines.push(`export type ${model.name} = {\n${scalars}\n};`);
    // Recursive payload resolver (handles nested select/include narrowing).
    lines.push(`export type ${model.name}GetPayload<A> = $Payload<"${model.name}", A>;`);
    lines.push(this.fluentType(model));
    return lines.join("\n");
  }

  /**
   * Fluent-API return type for single-record reads: a Promise of the payload
   * that also exposes a method per relation (to-many -> array; to-one ->
   * chainable fluent).
   */
  private fluentType(model: ModelNode): string {
    const n = model.name;
    const methods = relationFields(model).map((f) => {
      if (f.isList) {
        return `  ${f.name}<S extends Prisma.${f.type}FindManyArgs = {}>(args?: S): Promise<${f.type}GetPayload<S>[]>;`;
      }
      return `  ${f.name}<S extends Prisma.${f.type}FindFirstArgs = {}>(args?: S): ${f.type}Fluent<S, null>;`;
    });
    return `export type ${n}Fluent<A, Null = null> = Promise<${n}GetPayload<A> | Null> & {
${methods.join("\n")}
};`;
  }

  /**
   * Type-level registry powering recursive payload resolution: a model-name
   * union, a scalar-payload map, and a relation map carrying each relation's
   * target model, list-ness and nullability.
   */
  private registry(): string {
    const names = this.schema.models.map((m) => `"${m.name}"`).join(" | ");

    const scalarEntries = this.schema.models
      .map((m) => `  ${m.name}: ${m.name};`)
      .join("\n");

    const relationEntries = this.schema.models
      .map((m) => {
        const rels = relationFields(m)
          .map((f) => {
            const nullable = !f.isList && !f.isRequired ? "; isNullable: true" : "";
            return `    ${f.name}: { model: "${f.type}"; isList: ${f.isList}${nullable} }`;
          })
          .join(";\n");
        return `  ${m.name}: {${rels ? `\n${rels}\n  ` : ""}};`;
      })
      .join("\n");

    return `export type $ModelName = ${names || "never"};

export interface $ScalarPayload {
${scalarEntries}
}

export interface $RelationMap {
${relationEntries}
}`;
  }

  private scalarType(field: FieldNode): string {
    const base = baseTsType(field, this.schema);
    if (field.isList) return `${base}[]`;
    return field.isRequired ? base : `${base} | null`;
  }

  // ---- input types (Prisma namespace) -------------------------------------

  private namespace(): string {
    const blocks: string[] = [SHARED_FILTERS];
    for (const model of this.schema.models) {
      blocks.push(this.whereInput(model));
      blocks.push(this.orderByInput(model));
      blocks.push(this.selectInclude(model));
      blocks.push(this.dataInputs(model));
      blocks.push(this.argsTypes(model));
      blocks.push(this.delegateInterface(model));
    }
    return `export namespace Prisma {\n${indentBlock(blocks.join("\n\n"))}\n}`;
  }

  private whereInput(model: ModelNode): string {
    const fields: string[] = [];
    for (const f of model.fields) {
      if (f.kind === "object") {
        fields.push(`  ${f.name}?: ${this.relationFilter(f)};`);
      } else {
        fields.push(`  ${f.name}?: ${this.fieldFilter(f)};`);
      }
    }
    return `export type ${model.name}WhereInput = {
  AND?: ${model.name}WhereInput | ${model.name}WhereInput[];
  OR?: ${model.name}WhereInput[];
  NOT?: ${model.name}WhereInput | ${model.name}WhereInput[];
${fields.join("\n")}
};

export type ${model.name}WhereUniqueInput = ${this.whereUnique(model)};`;
  }

  private whereUnique(model: ModelNode): string {
    const uniques = new Set<string>();
    for (const f of model.fields) if (f.isId || f.isUnique) uniques.add(f.name);
    for (const f of model.primaryKey) uniques.add(f);
    const parts = [...uniques].map((name) => {
      const field = model.fields.find((x) => x.name === name)!;
      return `{ ${name}: ${baseTsType(field, this.schema)} }`;
    });
    const base = `Partial<${model.name}WhereInput>`;
    return parts.length ? `(${parts.join(" | ")}) & ${base}` : base;
  }

  private fieldFilter(field: FieldNode): string {
    const base = baseTsType(field, this.schema);
    const filterName = FILTER_FOR_SCALAR[field.type] ?? null;
    if (field.kind === "enum") {
      return `${base} | { equals?: ${base}; in?: ${base}[]; notIn?: ${base}[]; not?: ${base} }`;
    }
    if (filterName) return `${base} | ${filterName}`;
    return `${base}`;
  }

  private relationFilter(field: FieldNode): string {
    if (field.isList) {
      return `{ some?: ${field.type}WhereInput; every?: ${field.type}WhereInput; none?: ${field.type}WhereInput }`;
    }
    return `${field.type}WhereInput | { is?: ${field.type}WhereInput | null; isNot?: ${field.type}WhereInput | null } | null`;
  }

  private orderByInput(model: ModelNode): string {
    const fields = scalarFields(model)
      .map((f) => `  ${f.name}?: SortOrder;`)
      .join("\n");
    return `export type ${model.name}OrderByInput = {\n${fields}\n};`;
  }

  private selectInclude(model: ModelNode): string {
    const scalarSel = scalarFields(model)
      .map((f) => `  ${f.name}?: boolean;`)
      .join("\n");
    const relSel = relationFields(model)
      .map((f) => `  ${f.name}?: boolean | ${f.type}FindManyArgs;`)
      .join("\n");
    const include = relationFields(model)
      .map((f) => `  ${f.name}?: boolean | ${f.type}FindManyArgs;`)
      .join("\n");

    const listRelations = relationFields(model).filter((f) => f.isList);
    const countLine = listRelations.length
      ? `\n  _count?: boolean | { select?: { ${listRelations
          .map((f) => `${f.name}?: boolean`)
          .join("; ")} } };`
      : "";

    return `export type ${model.name}Select = {
${scalarSel}${relSel ? "\n" + relSel : ""}${countLine}
};

export type ${model.name}Include = {
${include || "  [k: string]: never;"}${countLine}
};`;
  }

  private dataInputs(model: ModelNode): string {
    // Foreign-key scalars can be supplied via their relation, so they are
    // optional in CreateInput (mirrors Prisma's CreateWithout* inputs).
    const foreignKeys = new Set<string>();
    for (const rel of relationFields(model)) {
      for (const fk of rel.relation?.fields ?? []) foreignKeys.add(fk);
    }
    const createScalars = scalarFields(model)
      .filter((f) => !isGeneratedOnCreate(f))
      .map((f) => {
        const optional =
          isOptionalOnCreate(f) || foreignKeys.has(f.name) ? "?" : "";
        return `  ${f.name}${optional}: ${this.inputScalarType(f)};`;
      });
    const createRelations = relationFields(model).map(
      (f) => `  ${f.name}?: ${this.nestedCreate(f)};`,
    );
    const updateScalars = scalarFields(model).map(
      (f) => `  ${f.name}?: ${this.updateScalarType(f)};`,
    );
    const updateRelations = relationFields(model).map(
      (f) => `  ${f.name}?: ${this.nestedUpdate(f)};`,
    );

    return `export type ${model.name}CreateInput = {
${[...createScalars, ...createRelations].join("\n")}
};

export type ${model.name}UpdateInput = {
${[...updateScalars, ...updateRelations].join("\n")}
};`;
  }

  private inputScalarType(field: FieldNode): string {
    const base = baseTsType(field, this.schema);
    if (field.isList) return `${base}[]`;
    return field.isRequired ? base : `${base} | null`;
  }

  /**
   * Update value for a scalar field: a bare value, `{ set }`, and — for numeric
   * fields — the atomic operators increment/decrement/multiply/divide.
   */
  private updateScalarType(field: FieldNode): string {
    const value = this.inputScalarType(field);
    if (field.isList) return value;
    const base = baseTsType(field, this.schema);
    if (NUMERIC_SCALARS.has(field.type)) {
      const nullable = field.isRequired ? "" : " | null";
      return `${value} | { set?: ${base}${nullable}; increment?: ${base}; decrement?: ${base}; multiply?: ${base}; divide?: ${base} }`;
    }
    return `${value} | { set?: ${value} }`;
  }

  private nestedCreate(field: FieldNode): string {
    const t = field.type;
    if (field.isList) {
      return `{ create?: ${t}CreateInput | ${t}CreateInput[]; connect?: ${t}WhereUniqueInput | ${t}WhereUniqueInput[]; connectOrCreate?: { where: ${t}WhereUniqueInput; create: ${t}CreateInput } | { where: ${t}WhereUniqueInput; create: ${t}CreateInput }[] }`;
    }
    return `{ create?: ${t}CreateInput; connect?: ${t}WhereUniqueInput; connectOrCreate?: { where: ${t}WhereUniqueInput; create: ${t}CreateInput } }`;
  }

  private nestedUpdate(field: FieldNode): string {
    const t = field.type;
    if (field.isList) {
      return `{ create?: ${t}CreateInput | ${t}CreateInput[]; connect?: ${t}WhereUniqueInput | ${t}WhereUniqueInput[]; disconnect?: ${t}WhereUniqueInput | ${t}WhereUniqueInput[]; set?: ${t}WhereUniqueInput | ${t}WhereUniqueInput[]; delete?: ${t}WhereUniqueInput | ${t}WhereUniqueInput[] }`;
    }
    return `{ create?: ${t}CreateInput; connect?: ${t}WhereUniqueInput; disconnect?: boolean }`;
  }

  private argsTypes(model: ModelNode): string {
    const n = model.name;
    return `export type ${n}Omit = Partial<Record<keyof ${n}, boolean>>;

export type ${n}FindManyArgs = {
  where?: ${n}WhereInput;
  orderBy?: ${n}OrderByInput | ${n}OrderByInput[];
  select?: ${n}Select;
  include?: ${n}Include;
  omit?: ${n}Omit;
  take?: number;
  skip?: number;
  cursor?: ${n}WhereUniqueInput;
  distinct?: (keyof ${n})[];
};

export type ${n}FindFirstArgs = ${n}FindManyArgs;

export type ${n}FindUniqueArgs = {
  where: ${n}WhereUniqueInput;
  select?: ${n}Select;
  include?: ${n}Include;
  omit?: ${n}Omit;
};

export type ${n}CreateArgs = {
  data: ${n}CreateInput;
  select?: ${n}Select;
  include?: ${n}Include;
  omit?: ${n}Omit;
};

export type ${n}CreateManyArgs = { data: ${n}CreateInput[]; skipDuplicates?: boolean };

export type ${n}CreateManyAndReturnArgs = {
  data: ${n}CreateInput[];
  select?: ${n}Select;
  omit?: ${n}Omit;
  skipDuplicates?: boolean;
};

export type ${n}UpdateArgs = {
  where: ${n}WhereUniqueInput;
  data: ${n}UpdateInput;
  select?: ${n}Select;
  include?: ${n}Include;
  omit?: ${n}Omit;
};

export type ${n}UpdateManyArgs = { where?: ${n}WhereInput; data: ${n}UpdateInput };

export type ${n}UpsertArgs = {
  where: ${n}WhereUniqueInput;
  create: ${n}CreateInput;
  update: ${n}UpdateInput;
  select?: ${n}Select;
  include?: ${n}Include;
  omit?: ${n}Omit;
};

export type ${n}DeleteArgs = { where: ${n}WhereUniqueInput; select?: ${n}Select; include?: ${n}Include };
export type ${n}DeleteManyArgs = { where?: ${n}WhereInput };

export type ${n}CountArgs = { where?: ${n}WhereInput; take?: number; skip?: number };

export type ${n}AggregateArgs = {
  where?: ${n}WhereInput;
  _count?: true | Partial<Record<keyof ${n}, boolean>>;
  _avg?: Partial<Record<keyof ${n}, boolean>>;
  _sum?: Partial<Record<keyof ${n}, boolean>>;
  _min?: Partial<Record<keyof ${n}, boolean>>;
  _max?: Partial<Record<keyof ${n}, boolean>>;
};

export type ${n}GroupByArgs = ${n}AggregateArgs & {
  by: (keyof ${n})[];
  having?: ${n}WhereInput;
  orderBy?: ${n}OrderByInput | ${n}OrderByInput[];
};`;
  }

  private delegateInterface(model: ModelNode): string {
    const n = model.name;
    return `export interface ${n}Delegate {
  findMany<A extends ${n}FindManyArgs>(args?: A): Promise<${n}GetPayload<A>[]>;
  findFirst<A extends ${n}FindFirstArgs>(args?: A): ${n}Fluent<A, null>;
  findFirstOrThrow<A extends ${n}FindFirstArgs>(args?: A): ${n}Fluent<A, never>;
  findUnique<A extends ${n}FindUniqueArgs>(args: A): ${n}Fluent<A, null>;
  findUniqueOrThrow<A extends ${n}FindUniqueArgs>(args: A): ${n}Fluent<A, never>;
  create<A extends ${n}CreateArgs>(args: A): Promise<${n}GetPayload<A>>;
  createMany(args: ${n}CreateManyArgs): Promise<{ count: number }>;
  createManyAndReturn<A extends ${n}CreateManyAndReturnArgs>(args: A): Promise<${n}GetPayload<A>[]>;
  update<A extends ${n}UpdateArgs>(args: A): Promise<${n}GetPayload<A>>;
  updateMany(args: ${n}UpdateManyArgs): Promise<{ count: number }>;
  upsert<A extends ${n}UpsertArgs>(args: A): Promise<${n}GetPayload<A>>;
  delete<A extends ${n}DeleteArgs>(args: A): Promise<${n}GetPayload<A>>;
  deleteMany(args?: ${n}DeleteManyArgs): Promise<{ count: number }>;
  count(args?: ${n}CountArgs): Promise<number>;
  aggregate(args?: ${n}AggregateArgs): Promise<Record<string, any>>;
  groupBy(args: ${n}GroupByArgs): Promise<Record<string, any>[]>;
}`;
  }

  // ---- client class -------------------------------------------------------

  private clientClass(): string {
    const delegates = this.schema.models
      .map((m) => `  declare readonly ${lowerFirst(m.name)}: Prisma.${m.name}Delegate;`)
      .join("\n");
    return `export type EmberClientOptions = {
  datasourceUrl?: string;
  datasource?: ClientOptions["datasource"];
  log?: ClientOptions["log"];
};

export class EmberClient extends EmberClientBase {
  constructor(options: EmberClientOptions = {}) {
    super({ schema: schemaDocument, ...options });
  }

${delegates}
}`;
  }
}

export function generateClientSource(schema: SchemaDocument): string {
  return new ClientGenerator(schema).generate();
}

/** Generate and write the client to `<outDir>/index.ts`. Returns the path. */
export function writeClient(schema: SchemaDocument, outDir: string): string {
  const source = generateClientSource(schema);
  const file = resolve(outDir, "index.ts");
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, source, "utf8");
  return file;
}

// ---- static template fragments -------------------------------------------

/**
 * Generic, recursive payload resolver shared by every model's GetPayload.
 * Resolves nested `select`/`include` narrowing to arbitrary depth using the
 * `$ScalarPayload` / `$RelationMap` registries emitted per schema.
 */
const PAYLOAD_RESOLVER = `type $Scalar<M extends $ModelName> = $ScalarPayload[M];
type $Relations<M extends $ModelName> = M extends keyof $RelationMap
  ? $RelationMap[M]
  : {};

// A relation sub-arg may be \`true\` (full payload) or a nested args object.
type $NormalizeArgs<Sub> = Sub extends object ? Sub : {};

type $RelationResult<Info, Sub> = Info extends {
  model: infer RM extends $ModelName;
  isList: infer L;
}
  ? L extends true
    ? $Payload<RM, $NormalizeArgs<Sub>>[]
    : Info extends { isNullable: true }
      ? $Payload<RM, $NormalizeArgs<Sub>> | null
      : $Payload<RM, $NormalizeArgs<Sub>>
  : never;

// To-many relation keys of a model (eligible for _count).
type $ListRelations<M extends $ModelName> = {
  [K in keyof $Relations<M>]: $Relations<M>[K] extends { isList: true }
    ? K
    : never;
}[keyof $Relations<M>];

type $CountResult<M extends $ModelName, C> = C extends { select: infer SC }
  ? { [K in keyof SC & $ListRelations<M>]: number }
  : { [K in $ListRelations<M> & string]: number };

type $CountPart<M extends $ModelName, A> = A extends { _count: infer C }
  ? { _count: $CountResult<M, C> }
  : {};

type $SelectResult<M extends $ModelName, S> = {
  [K in keyof S & keyof $Scalar<M>]: $Scalar<M>[K];
} & {
  [K in keyof S & keyof $Relations<M>]: $RelationResult<$Relations<M>[K], S[K]>;
} & $CountPart<M, S>;

type $IncludeResult<M extends $ModelName, I> = {
  [K in keyof I & keyof $Relations<M>]: $RelationResult<$Relations<M>[K], I[K]>;
} & $CountPart<M, I>;

export type $Payload<M extends $ModelName, A> = A extends { select: infer S }
  ? $SelectResult<M, S>
  : A extends { include: infer I }
    ? $Scalar<M> & $IncludeResult<M, I>
    : $Scalar<M>;`;

const NUMERIC_SCALARS = new Set(["Int", "BigInt", "Float", "Decimal"]);

const FILTER_FOR_SCALAR: Record<string, string> = {
  String: "StringFilter",
  Int: "IntFilter",
  BigInt: "BigIntFilter",
  Float: "FloatFilter",
  Decimal: "FloatFilter",
  Boolean: "BoolFilter",
  DateTime: "DateTimeFilter",
  Bytes: "BytesFilter",
  Json: "JsonFilter",
};

const SHARED_FILTERS = `export type StringFilter = {
  equals?: string;
  not?: string | StringFilter;
  in?: string[];
  notIn?: string[];
  lt?: string;
  lte?: string;
  gt?: string;
  gte?: string;
  contains?: string;
  startsWith?: string;
  endsWith?: string;
  mode?: QueryMode;
};

export type IntFilter = {
  equals?: number;
  not?: number | IntFilter;
  in?: number[];
  notIn?: number[];
  lt?: number;
  lte?: number;
  gt?: number;
  gte?: number;
};

export type FloatFilter = IntFilter;
export type BigIntFilter = {
  equals?: bigint;
  not?: bigint | BigIntFilter;
  in?: bigint[];
  notIn?: bigint[];
  lt?: bigint;
  lte?: bigint;
  gt?: bigint;
  gte?: bigint;
};

export type BoolFilter = { equals?: boolean; not?: boolean };

export type DateTimeFilter = {
  equals?: Date;
  not?: Date | DateTimeFilter;
  in?: Date[];
  notIn?: Date[];
  lt?: Date;
  lte?: Date;
  gt?: Date;
  gte?: Date;
};

export type BytesFilter = { equals?: Buffer; not?: Buffer };

// Firebird has no JSON SQL functions: filters operate on the serialized text.
// 'path' is accepted by the type but rejected at runtime on Firebird.
export type JsonFilter = {
  equals?: JsonValue;
  not?: JsonValue;
  string_contains?: string;
  string_starts_with?: string;
  string_ends_with?: string;
  path?: string[];
};`;

function isGeneratedOnCreate(field: FieldNode): boolean {
  return field.default?.function?.name === "autoincrement";
}

function isOptionalOnCreate(field: FieldNode): boolean {
  return !field.isRequired || !!field.default || field.isUpdatedAt || field.isList;
}

function indentBlock(text: string): string {
  return text
    .split("\n")
    .map((l) => (l ? "  " + l : l))
    .join("\n");
}
